apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"

  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: vietrandev.com
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: 80
  tls:
  - hosts:
    - vietrandev.com
    secretName: ingress-cert