apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend-service
          servicePort: 80