apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    {{ if and .Values.setUpSSLCert (eq .Values.setUpSSLCert true) }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuerName }}
    kubernetes.io/tls-acme: "true"
    {{ end }}

  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: vietrandev.com
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: 80
  tls:
  - hosts:
    - vietrandev.com
    secretName: ingress-cert